import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'video_mixer_settings.freezed.dart';

part 'video_mixer_settings.g.dart';

/// The type of image rendering mode.
@JsonEnum(fieldRename: FieldRename.snake)
enum VideoRenderingMode {
  /// The input buffer will be used as it is. No effects will be applied.
  passthrough,

  /// Off-screen rendering will be performed to allow for more flexible drawing.
  offscreen
}

/// Constraints on the video mixer settings.
///
/// This class represents configuration options for the video mixer,
/// including rendering mode, mute state, and the main video track index.
/// It is immutable and supports JSON serialization via `freezed` and
/// `json_serializable`.
@freezed
class VideoMixerSettings with _$VideoMixerSettings {
  const factory VideoMixerSettings({
    /// Specifies how video frames are rendered.
    ///
    /// If the value is missing or an unknown enum value is received from JSON,
    /// [VideoRenderingMode.offscreen] will be used as the default.
    @JsonKey(
      defaultValue: VideoRenderingMode.offscreen,
      unknownEnumValue: VideoRenderingMode.offscreen,
    )
    @Default(VideoRenderingMode.offscreen)
    VideoRenderingMode mode,

    /// Whether the video output is muted.
    ///
    /// When set to `true`, video frames are not rendered or mixed.
    @Default(false) bool isMuted,

    /// Index of the main video track.
    ///
    /// This value is typically used when multiple video tracks are available
    /// and one of them should be treated as the primary source.
    @Default(0) int mainTrack,
  }) = _VideoMixerSettings;

  /// Creates a [VideoMixerSettings] instance from a JSON map.
  ///
  /// This factory is generated by `json_serializable` and handles default
  /// values and unknown enum cases safely.
  factory VideoMixerSettings.fromJson(Map<String, dynamic> json) =>
      _$VideoMixerSettingsFromJson(json);
}
